### PR TITLE
add sponsor button in release note popup #940

### LINKED ISSUE #940: Add a link to website's sponsors page in the `ReleaseNotes` component
Link: https://responsively.app/sponsor/

Component link: https://github.com/responsively-org/responsively-app/blob/main/desktop-app/src/renderer/components/ReleaseNotes/index.tsx

Add a `Sponsor` button at the bottom of the Release Notes pop-up.

### PR DESCRIPTION
**Pull request by ReshadSadik**
# ✨ Pull Request

### 📓 Referenced Issue
This changes resolves #940 

**About the PR :**

Added "Sponsor" button in the ` ReleaseNotes ` component which will take us to the website [sponsor page](https://responsively.app/sponsor/) .

Here is a preview of the Release Notes popup .

image

Tested the app after adding new button and everything seems to be working properly .

### CODE REVIEW

**Comment by manojVivek** [comment]
@ReshadSadik Great work, implementing this so quickly! 👏🏼 👏🏼  

Just a minor feedback on the design, I think it would be better if move the `Close` and `Full Release Notes` button to the left and the `Sponsor` button to the `right` and modify the text on the button like below:
```
------------------------------------------------------------------------------------------------------
|   |Release Notes|   |Close|                                                                                |Support Responsively App| |
------------------------------------------------------------------------------------------------------

**Comment by ReshadSadik** [comment]
> @ReshadSadik Great work, implementing this so quickly! 👏🏼 👏🏼
> 
> Just a minor feedback on the design, I think it would be better if move the `Close` and `Full Release Notes` button to the left and the `Sponsor` button to the `right` and modify the text on the button like below:
> 
> ```
> ------------------------------------------------------------------------------------------------------
> | |Release Notes|   |Close|                                               |Support Responsively App| |
> ------------------------------------------------------------------------------------------------------
> ```

Sure thing ! I'll just do it quickly and submit a request @manojVivek

**Review by manojVivek — APPROVED** [review]
Looks good! Thank you so much for the contribution and looking forward to more like this! 🎉

**Comment by manojVivek** [comment]
@all-contributors Please add @ReshadSadik for code.

**Pull request merged**
