### PR TITLE
Export and import preferences

### PR DESCRIPTION
**Pull request by danielm2402**
# ✨ Pull Request

### 📓 Referenced Issue
#656 

### ℹ️ About the PR
Added buttons to export and import user preferences. I preferred to do the download and upload of the json file from the main process, from the renderer process there is a problem with the redux extension in development mode (I think it is a better solution to do it from the main process). I would love to read the proposals to improve UX to export / import buttons and about the configuration file which is currently a JSON.

### 🖼️ Testing Scenarios / Screenshots
[Uploading a config file with 3 custom devices and darkmode](https://www.loom.com/share/31a609e9ba394336a1d0579a11bb66c4)

I tested exporting and importing configurations between windows (10) and Linux (Debian bullseye)

### CODE REVIEW

**Comment by danielm2402** [comment]
> @danielm2402 Thanks you so much for working on this. This looks wonderful. 🎉 
> 
> Just a design suggestion, these options right now look too prominent/distracting. Shall we push it into a Kebab menu like this mockup below:
> Screenshot 2022-01-17 at 7 21 42 PM 1
> 
> Link to the Kebab Menu component: https://github.com/responsively-org/responsively-app/blob/master/desktop-app/app/components/KebabMenu.js

I really like your idea, I will make the respective changes

**Comment by manojVivek** [comment]
@danielm2402 Did you get a chance to look into it?

**Comment by danielm2402** [comment]
@manojVivek Hello, I was away a bit due to health problems, but before the weekend I will make the menu

**Comment by manojVivek** [comment]
No worries @danielm2402. 
Please take care of your health, this can wait for whenever you recovered and feeling good. 🙂

**Comment by danielm2402** [comment]
@manojVivek Sorry for taking so long, as I mentioned I had some health problems, but, I'm back and I want to help in this amazing project. I just added the kebab menu, I am looking forward to your reviews.

**Comment by manojVivek** [comment]
@danielm2402 Amazing, can you please add a screenshot of how it looks?

**Comment by danielm2402** [comment]
@manojVivek Of course

menukeb

**Comment by manojVivek** [comment]
@danielm2402 One suggestion, can you please make the options subtle like the ones in the screenshot below? 

Screenshot 2022-02-16 at 2 16 54 PM

**Comment by danielm2402** [comment]
@manojVivek Resolved. I remain attentive to your comments. Thank you very much

kebabitem

**Review by manojVivek — APPROVED** [review]
This is looking great, merging it now.

**Pull request merged**
