### PR TITLE
[#332] Added sections for browser extensions on the website

### PR DESCRIPTION
**Pull request by JayArya**
### Description
Website didn't had any mentions of the browser extensions.

### Changes Made
Added a section on website home page for browser extension using bootstrap elements only
Added a section on website download page with direct links to browser extensions

### CODE REVIEW

**Comment by manojVivek** [comment]
@JayArya Thank you so much for this PR! 🎉 

Can you please attach a screenshot of the section? Just to see how it looks before merging.

**Comment by JayArya** [comment]
@manojVivek Sorry! Should have done that in the first place. 

Got too excited for my first ever PR! 

Tried recreating video frame for the browser extension but couldn't match the quality of the other video frames. However, it can be added easily if someone can create the video.

# **Home Page Section**

- **Laptop**
Index - Generic Laptop - 2020-15-8 at 12 03 36 PM

- **iPad**
Index - iPad - 2020-15-8 at 12 04 49 PM

- **iPhone X**
Index - iPhone X - 2020-15-8 at 12 05 07 PM

- **Pixel 2**
Index - Pixel 2 - 2020-15-8 at 12 04 58 PM


# **Download Page Section**

- **Laptop**
Github - Generic Laptop - 2020-15-8 at 12 08 55 PM

- **iPad**
Github - iPad - 2020-15-8 at 12 08 20 PM

- **iPhone X**
Github - iPhone X - 2020-15-8 at 12 08 42 PM

- **Pixel 2**
Github - Pixel 2 - 2020-15-8 at 12 08 33 PM

**Comment by manojVivek** [comment]
@JayArya No worries, thanks for attaching the screenshots. 

I was thinking, to give it special attention, we shouldn't add it to the features list. Instead, it will be great, if we could create a new section like the one attached below and add the links there. 

Screenshot 2020-08-15 at 12 56 31 PM

Maybe we can add this section below the features list and above the footer.

**Comment by JayArya** [comment]
@manojVivek I like the idea of adding a new section.

This is how it looks **between the feature list and footer**

Screenshot (39)




Do you have any suggestions for the **Download** page edits?

Screenshot (42)

**Comment by manojVivek** [comment]
The homepage one looks great. 👏  

> Do you have any suggestions for the **Download** page edits?

Maybe we can try the same design for the downloads page too? Just above the footer. What do you think?

**Comment by JayArya** [comment]
@manojVivek 

This is how it looks with the same design

Screenshot (43)


TBH, I like the consistent look of the cards in the earlier edit

Screenshot (42)


While I was at it I did this one too but still the edits above are better IMO.

Screenshot (44)

**Comment by manojVivek** [comment]
@JayArya My primary concern about the last two designs is that the app download and extension links are so close that it might be confusing to the users.

I like the first one though, it has that distinction between the app download and extension.

**Comment by JayArya** [comment]
@manojVivek Made some minor changes to improve the seggregation

Screenshot (45)


But I agree, separate sections are a better option.  We should go ahead with this

Screenshot (43)

**Comment by manojVivek** [comment]
> But I agree, separate sections are a better option. We should go ahead with this

Yeah agreed. Please let me know when that change is ready.

**Comment by JayArya** [comment]
@manojVivek it is ready.

I have pushed to my JayArya:master

**Comment by manojVivek** [comment]
@JayArya Thank you so much for your contribution and patience with the review. Merging this in now. 🎉 

Looking forward to more like this in the future. 🙌

**Comment by manojVivek** [comment]
@all-contributors Please add @JayArya for code.

**Comment by manojVivek** [comment]
@JayArya Two things:

1. Can you let us know your Twitter handle? We would love to give a shout out for your work from our twitter account.
2. Please join our community on Gitter - https://gitter.im/responsively-app/, for any discussions in the future.

**Comment by JayArya** [comment]
@manojVivek Thank You! Thanks for helping with my first Open Source contribution (ever!).

Twitter Handle: @JayanArya

I love Responsively and it has been **very helpful**. Looking forward for future contributions! 🙌

**Pull request merged**
