### PR TITLE
Fix - Problem with right-docked devtools

### LINKED ISSUE #530: When devtools is right-docked, items above cannot be clicked
# 🐞 (Original) bug report

### ✍️ Description

If I try and open the Live CSS editor when devtools is open it won't all me to open the live css editor. I have to open live css editor then dev tools to have them both open at the same time.

### 🕵🏼‍♂️ Is this a regression?

Live CSS editor was not in previous version

### 🔬 Minimal Reproduction

Open program
Load website
Toggle Live CSS Editor to on
Inspect an element to open dev tools
Attempt to toggle off the Live CSS editor - Hand to click does not appear

### 🔥 Exception or Error or Screenshot

<pre><code>

</code></pre>

see: https://github.com/responsively-org/responsively-app/issues/530#issuecomment-722350840

### PR DESCRIPTION
**Pull request by p4nu**
# ✨ Pull Request

### 📓 Referenced Issue

Fixes #530 

### ℹ️ About the PR

Change the resizer size and toolbar position to fix the non-clickable icons when devtools are right-docked.

### 🖼️ Testing Scenarios / Screenshots

Animation

### CODE REVIEW

**Comment by manojVivek** [comment]
@p4nu This is amazing. This is a long awaited fix, thank you so much for working on it. AFK for a week, I'll take a look at after. 🚕

**Comment by p4nu** [comment]
My pleasure! 😊
Take your time, no rush 👍

**Review by jjavierdguezas — APPROVED** [review]

**Comment by p4nu** [comment]
@jjavierdguezas Is the separate issue made for it? I don't think my solution has made that thing happen. I only changed sizes of components, not zindex.

**Comment by jjavierdguezas** [comment]
> @jjavierdguezas Is the separate issue made for it? I don't think my solution has made that thing happen. I only changed positions of components, not zindex.

 your code is fine and solves the original issue. I just pointed out a new issue that we can see now that we can click those elements.
we should merge this PR and create a separate issue

**Comment by manojVivek** [comment]
@p4nu Going to merge this, thanks again for the fix. ❤️ 

@jjavierdguezas Thanks for testing the fix! ❤️

**Comment by manojVivek** [comment]
@all-contributors Please add @p4nu for code.

**Pull request merged**
