### PR TITLE
fix , file has an # in the name, it does not open with responsively

### PR DESCRIPTION
**Pull request by mrfelfel**
automatic format filepath to file url  

fix

### CODE REVIEW

**Comment by jjavierdguezas** [comment]
hi @mrfelfel, do this PR target the same issue as #398?

**Comment by mrfelfel** [comment]
yes, I think that's the wrong way

**Comment by jjavierdguezas** [comment]
Great @mrfelfel merging it now

**Comment by jjavierdguezas** [comment]
@all-contributors Please add @mrfelfel for code.

**Comment by jjavierdguezas** [comment]
@mrfelfel:
- Can you let us know your Twitter handle? We would love to give a shout out for your work from our twitter account.
- Please join our community on [Slack](https://join.slack.com/t/responsively/shared_invite/zt-h0ouywhs-IIeHj39ymz5IOrgcOa_tRA), for any discussions in the future.

**Comment by mrfelfel** [comment]
https://twitter.com/mrfelfeldolme my twitter account

**Pull request merged**
