### PR TITLE
Fixed persistent hover effect

### PR DESCRIPTION
**Pull request by JLambertazzo**
This is a fix to issue https://github.com/responsively-org/responsively-app/issues/388

The cause of the bug was that the state of the pointer (mouse/touch) was updated as the pointer left the button. With this fix, the state is updated on mouse movement within the button, giving it a more responsive feel.

### CODE REVIEW

**Comment by jjavierdguezas** [comment]
Hi @JLambertazzo this looks good! thanks
It is posible to hide the tooltip too? it keeps open even when the pointer is far away
image

**Comment by jjavierdguezas** [comment]
@JLambertazzo can you please make a comment in #388 in order to assign it to you (We can't if you haven't interacted with the issue.)

**Comment by JLambertazzo** [comment]
I can take a look at the tooltip issue!

**Comment by JLambertazzo** [comment]
The problem with the tooltip sticking around was happening because, when touch mode is entered the mouse stays hovered on the toggle button until user is no longer in touch mode. I fixed the issue by hiding the tooltip while in touch mode!
fix

**Comment by jjavierdguezas** [comment]
@JLambertazzo  others buttons always shows tooltip on hover, in order to be consistent, why don't you try a combination of the `open` prop of `<Tooltip ...>` and `onMouseEnter` , `onMouseLeave`, `onPointerEnter` and `onPointerLeave` events? Just an idea
`onXXXXEnter => open = true`
`onXXXXLeave => open = false`
what do you think?

**Comment by JLambertazzo** [comment]
Unfortunately once in touch mode hover is no longer triggered by hovering the cursor over, rather you would need to click and hold to have the same hover effect. These are the results I got when trying to listen and log any focus/pointer/mouse/touch events, which showed me that in touch mode moving the mouse doesn't trigger any of these events.

prob

I was however able to implement consistent behavior for the touch mode icon with all other icons. The other icons would show tooltips in touch mode when you would click and hold them, and now the toggle touch mode button does the same. As for the persistent hover issue, the tooltip sticking around, those issues are fixed and even some of the inconsistency is dealt with. However, the inconsistent behavior between toggle buttons actually seems to be a much deeper issue, and should therefore have it's own issue thread. I'll join the slack to discuss the problem further, unless there is a better place to do so.

**Comment by jjavierdguezas** [comment]
Sorry @JLambertazzo  now there is a weird behavior with the tooltip
touch
If the pointer/mouse events don't fire on touch mode I prefer your initial solution where there is no tooltip on touch mode
`touchMode = true => tooltip = ""`
I rolled back to your initial solution,
Now I merging this, thanks

**Comment by jjavierdguezas** [comment]
@JLambertazzo Thanks so much for your code contribution.
Looking forward to more collaboration in the future! 💪🏻

**Comment by jjavierdguezas** [comment]
@all-contributors Please add @JLambertazzo for code.

**Comment by jjavierdguezas** [comment]
@JLambertazzo Do you might sharing your Twitter handle? We would love to send a shout out for your work on twitter. :)
And please join our slack workspace for any future discussions: https://join.slack.com/t/responsively/shared_invite/zt-haoieftz-IsMw64H6jXC23pJ16ROLzw :)

**Comment by JLambertazzo** [comment]
That would be great, thank you! My twitter handle is @JLambertazzo. I'll reach out on slack.

**Comment by jjavierdguezas** [comment]
> That would be great, thank you! My twitter handle is @JLambertazzo. I'll reach out on slack.

cc: @manojVivek

**Pull request merged**
