### PR TITLE
Feature/767 accept language

### PR DESCRIPTION
**Pull request by happymvp**
# ✨ Pull Request

### 📓 Referenced Issue

 Resolves: #767

### ℹ️ About the PR

Added new setting section with Request Headers parameter. 

Potentially interesting topic to discuss: Adding default values resolution as described in https://github.com/sindresorhus/electron-store/issues/92.

For me this is valid issue and default value of electron store never showed up.

### 🖼️ Testing Scenarios / Screenshots

Screenshot 2024-10-28 at 08 24 38

Screenshot 2024-10-28 at 08 24 29

Screenshot 2024-10-28 at 08 25 57

Screenshot 2024-10-28 at 08 26 05

### CODE REVIEW

**Review by violetadev — APPROVED** [review]

**Comment by violetadev** [comment]
> Test / test (macos-latest) (pull_request) error: Error: node_modules/@jest/environment/build/index.d.ts(327,26): error TS2430: Interface 'JestImportMeta' incorrectly extends interface 'ImportMeta'.
> 
> Doesn't seem like error I should deal with as part of this PR

I am not able to merge this pr until this has been resolved, it simply doesn't let me merge with pipeline errors, and it seems that this has been raised from your changes as we merged other prs just fine before this one. Could you take a look? 
Thanks

**Comment by happymvp** [comment]
> > Test / test (macos-latest) (pull_request) error: Error: node_modules/@jest/environment/build/index.d.ts(327,26): error TS2430: Interface 'JestImportMeta' incorrectly extends interface 'ImportMeta'.
> > Doesn't seem like error I should deal with as part of this PR
> 
> I am not able to merge this pr until this has been resolved, it simply doesn't let me merge with pipeline errors, and it seems that this has been raised from your changes as we merged other prs just fine before this one. Could you take a look? Thanks

Now everything is correct

**Comment by violetadev** [comment]
thank you for your contributions!

@all-contributors Please add @happymvp for code

**Comment by violetadev** [comment]
@all-contributors  Please add @happymvp for test

**Pull request merged**
