### PR TITLE
Electron 9 minor version upgrade

### PR DESCRIPTION
**Pull request by manojVivek**

### CODE REVIEW

**Review by sidthesloth92 — APPROVED** [review]

**Comment by sidthesloth92** [comment]
@manojVivek Do we have test suites to ensure functionality is not broken?

**Comment by manojVivek** [comment]
> @manojVivek Do we have test suites to ensure functionality is not broken?

@sidthesloth92 Unfortunately we don't have unit test suites. 😓 
I have manually tested most of the workflow. Also checked all the release notes from the previous version to the current one and there is no breaking change in any of those. So we should be good, I believe.

**Comment by sidthesloth92** [comment]
That's some testing..👏 The problem though is that everyone doesn't have same app knowledge like you.. :( (Including me) I was little scared when I committed code to be honest.. 😅 Should we create an issue? [Specton](https://www.electronjs.org/spectron) seems to be promising.

**Comment by manojVivek** [comment]
> Should we create an issue? [Specton](https://www.electronjs.org/spectron) seems to be promising.

Yep, we should definitely start building a test suite. I'll create an issue from your comment.

**Review by jjavierdguezas — APPROVED** [review]

**Pull request merged**
